# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme:          "mmistakes/minimal-mistakes"
# theme:              "minimal-mistakes-jekyll"

minimal_mistakes_skin: "aqua" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "es-ES"
title: ISISTAN
title_separator          : "-"
subtitle                 : "Instituto superior de ingeniería de software"
description: >- # this means to ignore newlines until "baseurl:"
  El Instituto Superior de Ingeniería de Software de Tandil (ISISTAN) es una Unidad Ejecutora (UE) de doble dependencia UNCPBA-CONICET, creada en el año 2011 a partir del Núcleo de Actividades Científico - Tecnológicas denominado Instituto de Sistemas Tandil (ISISTAN). Forma parte del CCT-Tandil, dependiente del CONICET, y de la Facultad de Ciencias Exactas de la UNCPBA.. El ISISTAN realiza actividades de investigación y desarrollo en las Ciencias de la Computación, destacándose en las áreas de Ingeniería de Software e Inteligencia Artificial
logo                     : /assets/images/logo.png # path of logo image to display in the masthead, e.g. "/assets/images
twitter_username: ISISTAN_CONICET
github_username: 
url: "https://alezunino.github.io/isistan-web/"
repository:            alezunino/isistan-web
github:                [metadata]
search:                false
search_full_content:   true # true, false (default)
search_provider:       algolia # lunr (default), algolia
# reindexar con ALGOLIA_API_KEY='...' jekyll algolia 
algolia:               # registrado como alejandro.zunino@isistan
  nodes_to_index:      'p,blockquote,li,table'
  application_id:      UR16THV63B # YOUR_APPLICATION_ID
  index_name:          isistan # YOUR_INDEX_NAME
  search_only_api_key: 97cbce883464ed524be602d2730ad03f # YOUR_SEARCH_ONLY_API_KEY
  powered_by:          true # true (default), false
  files_to_exclude:
    #- _posts/2017-11-28-post-exclude-search.md
    #    - rrhh.md

# SEO Related
google_site_verification : # Replace this with your ID, or delete
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "ISISTAN_CONICET"
facebook:
  username               : &facebook "isistan.conicet"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/ISISTAN_CONICET"
    - "https://www.facebook.com/isistan.conicet/"


# Build settings
markdown: kramdown
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /novedades/page:num/
timezone: America/Argentina/Buenos_Aires # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Collections
collections:
  capacidades:
    output: true
    permalink: /:collection/:path/
  tecnologias:
    output: true
    permalink: /:collection/:path/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- Gemfile-dev
- Session.vim
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #  - jemoji
  - jekyll-include-cache

author:
  name   : "ISISTAN"
  #  avatar : "/assets/images/logo.png"
  bio    : "UNCPBA & CONICET"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ISISTAN_CONICET"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/isistan.conicet/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "https://spamty.eu/show/v6/1068/43d50a9c963e7be954d12cb8"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.isistan.unicen.edu.ar/"
    - label: "Dirección"
      icon: "fas fa-fw fa-map-marked"
      url: "https://goo.gl/maps/5AJMzBEjGm5w73Qf9"
    - label: "+54 249 4385650"
      icon: "fas fa-fw fa-phone"
      url: "tel:+54-249-4385650"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ISISTAN_CONICET"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/isistan.conicet/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "https://spamty.eu/show/v6/1199/4f3e7fad57d11e80055ce7b6/"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.isistan.unicen.edu.ar/"
    - label: "Dirección"
      icon: "fas fa-fw fa-map-marked"
      url: "https://goo.gl/maps/5AJMzBEjGm5w73Qf9"
    - label: "+54 249 4385650"
      icon: "fas fa-fw fa-phone"
      url: "tel:+54-249-4385650"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
